### ISSUE TITLE
Race conditions can ruin the data coming back from LX Sentai

### ISSUE THREAD

**Issue by tone81** [tone81/lx-sentai#8]
To Recreate:

1. Have two different people execute the request for a pose at the same time
1. First result comes back correctly
1. Second result munges some data from the first result with its result

**Comment by dijonkitchen** [comment]
Surprised this happens with concurrency, immutable data, and pure functional programming!

**Comment by tone81** [comment]
We should verify the recreate is still right when we're deciding on new poses.

**Comment by tone81** [comment]
Just my imagination.
